frameworkVersion: ">=1.32.0"

service: AutoAoiScene

package:
  individually: true
  exclude:
    - ./**
  include:
    - handler.py

custom: ${file(../common.yml)}

provider:
  name: aws
  stage: ${opt:stage, 'development'}
  region: ${opt:region, 'us-west-2'}
  deploymentBucket:
    name: ${self:custom.sourceCodeBucket.${self:provider.stage}}
    serverSideEncryption: AES256
  deploymentPrefix: syn-ai
  stackTags:
    project: syn-ai
    version: v2
    environment: ${self:provider.stage}

functions:
  AutoAoiScene:
    runtime: python3.6
    memorySize: 1024
    handler: handler.main
    description: Calculate scenes in the video for the AOIs
    name: syn-ai-aaoi-scene-${self:provider.stage}
    timeout: 900
    role: AutoAoiSceneRole

resources:
  - ${file(resources.yml)}

plugins:
  - serverless-python-requirements
